// Generated by Finicky Kickstart
// Save as ~/.finicky.js

export default {
  defaultBrowser: "Firefox",
  handlers: [
    {
      match: /^https?:\/\/linear\.app\//,
      browser: "Linear",
    },
    {
      match: /^https?:\/\/open\.spotify\.com\//,
      // match: finicky.matchDomains("open.spotify.com"),
      browser: "com.spotify.client",
    },
    {
      match: /^https?:\/\/spotify\.link\//,
      // match: finicky.matchDomains("open.spotify.com"),
      browser: "com.spotify.client",
    },
    {
      match: /^https?:\/\/meet\.google\.com\//,
      browser: "Google Chrome",
    },
    {
      match: /^https?:\/\/zoom\.us\/join/,
      browser: "us.zoom.xos",
    },
    {
      match: /^https?:\/\/teamengineltd\.slack\.com\/archive/,
      browser: "Slack",
    },
    {
      match: /^https?:\/\/localhost(:\d+)?\//,
      browser: "Google Chrome",
    },
    {
      match: /^https?:\/\/easguardians\.com\//,
      browser: "Google Chrome",
    },
  ],
};
