code --install-extension alefragnani.project-manager
code --install-extension arturock.gitstash
code --install-extension ckolkman.vscode-postgres
code --install-extension codezombiech.gitignore
code --install-extension dbaeumer.vscode-eslint
code --install-extension EliverLara.andromeda
code --install-extension Equinusocio.vsc-material-theme
code --install-extension Everspace.rightclick-git
code --install-extension JakeBecker.elixir-ls
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension oderwat.indent-rainbow
code --install-extension paragdiwan.gitpatch
code --install-extension pgourlain.erlang
code --install-extension PKief.material-icon-theme
code --install-extension pomber.git-file-history
code --install-extension Prisma.vscode-graphql
code --install-extension redhat.vscode-yaml
code --install-extension salesforce.salesforcedx-vscode
code --install-extension syler.sass-indented
code --install-extension waderyan.gitblame
code --install-extension ziyasal.vscode-open-in-github
