name: CI

on:
  push:

jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup tools
        uses: jdx/mise-action@v2

      - run: just check
